import { RawTypesConfig, AvoidOptionalsConfig } from '@graphql-codegen/visitor-plugin-common';

/**
 * @description This plugin generates the base python types, based on your GraphQL schema.
 *
 * The types generated by this plugin are simple, and refers to the exact structure of your schema, and it's used as the base types for other plugins (such as `python-operations`)
 */
export interface PythonPluginConfig extends RawTypesConfig {
  /**
   * @description This will cause the generator to avoid using python optionals (`?`) on types,
   * so the following definition: `type A { myField: String }` will output `myField: Maybe<string>`
   * instead of `myField?: Maybe<string>`.
   * @default false
   *
   * @exampleMarkdown
   * ## Override all definition types
   * ```yml
   * generates:
   * path/to/file.ts:
   *  plugins:
   *    - python
   *  config:
   *    avoidOptionals: true
   * ```
   *
   * ## Override only specific definition types
   * ```yml
   * generates:
   * path/to/file.ts:
   *  plugins:
   *    - python
   *  config:
   *    avoidOptionals:
   *      field: true
   *      inputValue: true
   *      object: true
   *      defaultValue: true
   * ```
   */
  avoidOptionals?: boolean | AvoidOptionalsConfig;
  /**
   * @description Will prefix every generated `enum` with `const`, you can read more about const enums here: https://www.pythonlang.org/docs/handbook/enums.html.
   * @default false
   *
   * @exampleMarkdown
   * ```yml
   * generates:
   * path/to/file.ts:
   *  plugins:
   *    - python
   *  config:
   *    constEnums: true
   * ```
   */
  constEnums?: boolean;
  /**
   * @description Generates enum as python `type` instead of `enum`. Useful it you wish to generate `.d.ts` declaration file instead of `.ts`
   * @default false
   *
   * @exampleMarkdown
   * ```yml
   * generates:
   * path/to/file.ts:
   *  plugins:
   *    - python
   *  config:
   *    enumsAsTypes: true
   * ```
   */
  enumsAsTypes?: boolean;
  /**
   * @description Controls whether to preserve python enum values as numbers
   * @default false
   *
   * @exampleMarkdown
   * ```yml
   * generates:
   * path/to/file.ts:
   *  plugins:
   *    - python
   *  config:
   *    numericEnums: true
   * ```
   */
  numericEnums?: boolean;
  /**
   * @description This option controls whether or not a catch-all entry is added to enum type definitions for values that may be added in the future. You also have to set `enumsAsTypes` to true if you wish to use this option.
   * This is useful if you are using `relay`.
   * @default false
   *
   * @exampleMarkdown
   * ```yml
   * generates:
   * path/to/file.ts:
   *  plugins:
   *    - python
   *  config:
   *    enumsAsTypes: true
   *    futureProofEnums: true
   * ```
   */
  futureProofEnums?: boolean;
  /**
   * @description This option controls whether or not a catch-all entry is added to union type definitions for values that may be added in the future.
   * This is useful if you are using `relay`.
   * @default false
   *
   * @exampleMarkdown
   * ```yml
   * generates:
   * path/to/file.ts:
   *  plugins:
   *    - python
   *  config:
   *    futureProofUnions: true
   * ```
   */
  futureProofUnions?: boolean;
  /**
   * @description Generates enum as python `const assertions` instead of `enum`. This can even be used to enable enum-like patterns in plain JavaScript code if you choose not to use python’s enum construct.
   * @default false
   *
   * @exampleMarkdown
   * ```yml
   * generates:
   * path/to/file.ts:
   *  plugins:
   *    - python
   *  config:
   *    enumsAsConst: true
   * ```
   */
  enumsAsConst?: boolean;
  /**
   * @description This will cause the generator to emit types for operations only (basically only enums and scalars).
   * Interacts well with `preResolveTypes: true`
   * @default false
   *
   * @exampleMarkdown Override all definition types
   * ```yml
   * generates:
   * path/to/file.ts:
   *  plugins:
   *    - python
   *  config:
   *    onlyOperationTypes: true
   * ```
   */
  onlyOperationTypes?: boolean;
  /**
   * @description Generates immutable types by adding `readonly` to properties and uses `ReadonlyArray`.
   * @default false
   *
   * @exampleMarkdown
   * ```yml
   * generates:
   * path/to/file.ts:
   *  plugins:
   *    - python
   *  config:
   *    immutableTypes: true
   * ```
   */
  immutableTypes?: boolean;
  /**
   * @description Allow to override the type value of `Maybe`.
   * @default T | null
   *
   * @exampleMarkdown
   * ## Allow undefined
   * ```yml
   * generates:
   *  path/to/file.ts:
   *    plugins:
   *      - python
   *    config:
   *      maybeValue: T | null | undefined
   * ```
   *
   * ## Allow `null` in resolvers:
   * ```yml
   * generates:
   *  path/to/file.ts:
   *    plugins:
   *      - python
   *      - python-resolvers
   *    config:
   *      maybeValue: 'T extends PromiseLike<infer U> ? Promise<U | null> : T | null'
   * ```
   */
  maybeValue?: string;
  /**
   * @description Set to `true` in order to generate output without `export` modifier.
   * This is useful if you are generating `.d.ts` file and want it to be globally available.
   * @default false
   *
   * @exampleMarkdown
   * ## Disable all export from a file
   * ```yml
   * generates:
   * path/to/file.ts:
   *  plugins:
   *    - python
   *  config:
   *    noExport: true
   * ```
   */
  noExport?: boolean;
  /**
   * @description Set the value to `true` in order to disable all description generation.
   * @default false
   *
   * @exampleMarkdown
   * ## Disable description generation
   * ```yml
   * generates:
   * path/to/file.ts:
   *  plugins:
   *    - python
   *  config:
   *    disableDescriptions: true
   * ```
   */
  disableDescriptions?: boolean;
  /**
   * @description When a GraphQL interface is used for a field, this flag will use the implementing types, instead of the interface itself.
   * @default false
   *
   * @exampleMarkdown
   * ## Override all definition types
   * ```yml
   * generates:
   * path/to/file.ts:
   *  plugins:
   *    - python
   *  config:
   *    useImplementingTypes: true
   * ```
   */
  useImplementingTypes?: boolean;
  /**
   * @name wrapEntireFieldDefinitions
   * @type boolean
   * @description Set the to `true` in order to wrap field definitions with `EntireFieldWrapper`.
   * This is useful to allow return types such as Promises and functions for fields.
   * Differs from `wrapFieldDefinitions` in that this wraps the entire field definition if ie. the field is an Array, while
   * `wrapFieldDefinitions` will wrap every single value inside the array.
   * @default true
   *
   * @example Enable wrapping entire fields
   * ```yml
   * generates:
   * path/to/file.ts:
   *  plugins:
   *    - python
   *  config:
   *    wrapEntireFieldDefinitions: false
   * ```
   */
  wrapEntireFieldDefinitions?: boolean
  /**
   * @name entireFieldWrapperValue
   * @type string
   * @description Allow to override the type value of `EntireFieldWrapper`. This wrapper applies outside of Array and Maybe
   * unlike `fieldWrapperValue`, that will wrap the inner type.
   * @default T | Promise<T> | (() => T | Promise<T>)
   *
   * @example Only allow values
   * ```yml
   * generates:
   * path/to/file.ts:
   *  plugins:
   *    - python
   *  config:
   *    entireFieldWrapperValue: T
   * ```
   */;
  entireFieldWrapperValue?: string;
}